In [ ]:
# 1.	Write a Python program which accept the radius of a circle from the user and compute the area.

radius=int(input("Enter the radius of the Circle: "))
area= 3.14*(radius**2)
print(f"Area of the Circle is: {area}")


Enter the radius of the Circle: 12
Area of the Circle is: 452.16


In [ ]:
# 2.	Write a Python program to calculate number of days between two dates.

from datetime import date

date1 = date(2022, 11, 1)
date2 = date(2022, 11, 30)
d = date2 - date1
print(d.days)


29


In [ ]:
# 3.	Write a Python program to test whether a passed letter is a vowel or not.

letter=input("Enter the letter: ")
letter1=letter.lower()
if letter1 in ('a','e','i','o','u'):
  print(f'{letter1}: The letter is vowel.')
else:
  print(f'{letter1}: The letter is consonant.')
    

Enter the letter: c
c: The letter is consonant.


In [ ]:
# 4.	Write a program to print every character of a string entered by the user in a new line using a loop.

str=input("Enter the string: ")
for i in range(0,len(str)):
  print(str[i])

Enter the string: divya m
d
i
v
y
a
 
m


In [21]:
# 5.	Python program to check whether a number is Prime or not.

num=int(input("Enter the number: "))

for i in range(2,num+1):
  if i==num:
    print(f'{num} is prime')
    #print("i1",i)
    break
  elif num%i==0:
    #print("i2",i)
    print(f'{num} is not prime')
    break

Enter the number: 211
211 is prime


In [ ]:
# 6.	Python program to Count Even and Odd numbers in a string.

stri = 'numpyarray' 
even=[]
odd=[]
for i in range(0,len(stri)):
  if i%2==0:
    even.append(stri[i])
      # print(stri.count(stri[i]))
  else:
    odd.append(stri[i])
print(even)
print(odd)
even_count=0
odd_count=0

for i in range(len(even)):
  even_count=even_count+1
print(f"even count: {even_count}")

for i in range(len(odd)):
  odd_count=odd_count+1
print(f"odd count: {odd_count}")
  

['n', 'm', 'y', 'r', 'a']
['u', 'p', 'a', 'r', 'y']
even count: 5
odd count: 5


In [ ]:
# 7.	Write a Python program to find the second most repeated word in a given string.

string='abcabbaa'
c2=[]
for i in range(0,len(string)):
  c1=string.count(string[i])
  alp=string[i]
  print(f'{alp}:{c1}')


a:4
b:3
c:1
a:4
b:3
b:3
a:4
a:4


In [ ]:
# 8.	Python program to interchange first and last elements in a list.

string='divyamaurya'
first=string[0:1]
print(first)
last=string[-1:]
print(last)
mid=string[1:-1]
print(mid)

final=last+mid+first
print(final)


d
a
ivyamaury
aivyamauryd


In [ ]:
# 9. How to sort a list in ascending and descending order without using the sort function?

#   considering all the elements as integers

list_in = [10,20,5,8,33,120,85,65]
list_f = []

while list_in:
    mini = list_in[0] 
    for i in list_in: 
        if i < mini:
            mini = i
    list_f.append(mini)
    list_in.remove(mini)    
print (list_f)

[5, 8, 10, 20, 33, 65, 85, 120]


In [ ]:
# 10.	Python program to sort Python Dictionaries by Values.

mydict={'Harry':2,
        'Sejal':10,
        'Kartik':5}
print(type(mydict))

{key: value for key, value in sorted(mydict.items(), key=lambda item: item[1])}

<class 'dict'>


{'Harry': 2, 'Kartik': 5, 'Sejal': 10}

In [26]:
# 11 Create a list of tuples from the given list having a number and its cube in each tuple.

num=[2,4,6]
li=[]

for i in range(0,len(num)):
  a=(num[i],num[i]*num[i]*num[i])
  # print(a)
  li.append(a)
print(li)

[(2, 8), (4, 64), (6, 216)]


In [ ]:
# 12.	How to extract all numbers between a given range from a NumPy array?

import numpy as np

arr=np.array([12,10,5,15,17,11,21,6,8,19])
print(arr)
ra=[]
for i in range(0,len(arr)):
  if arr[i]>10 and arr[i]<20:
    ra.append(arr[i])
print(ra)



[12 10  5 15 17 11 21  6  8 19]
[12, 15, 17, 11, 19]


In [ ]:
# 13.How to convert 4D array to 2D array?
import numpy as np    
arr = np.arange(72)
arr = np.reshape(a, (4,3,2,3))
# print(arr)
print(arr.shape)
brr=np.reshape(arr,(8,9))
print(brr)
print(brr.shape)

(4, 3, 2, 3)
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
(8, 9)


In [ ]:
# 14.	Suppose there is room with a round table with 100 empty.......................

player = [i for i in range(1,101)]
while len(player)>2:
  #print(player)
  #print(len(player))
  rem = []
  for i in range(0,len(player),2):
    rem.append(player[i])
  #print("rem after append",rem)
  rem = [rem[-1]] + [player[-1]] + rem[0:-1]
  #print("rem suffled",rem)
  rem = list(dict.fromkeys(rem))
  #print(i)
  #print("final rem",rem)
  player = rem
  #print(rem)
  #print(player)

print(player[0])


73


In [ ]:
# 15.	Search Pivot index in the Array.

nums = [1,7,1]
if len(nums)<3:
  print("i need more data points")
pivt = []
for i in range(1,len(nums)-1):
  sumL=0
  sumR=0
  for j in range(0,i):
    sumL=sumL+nums[j]
  #print(i,sumL)
  for j in range(i+1,len(nums)):
    sumR=sumR+nums[j]
  #print(i,sumR)
  if (sumL==sumR):
    pivt.append(i)
print("pivot indexes are : ",pivt)


pivot indexes are :  [1]


In [ ]:
# 16.	Check if a String is an Anagram

fir='anagram'
bir='aagramn'
aa=[]
bb=[]
for i in range(0,len(fir)):
  aa.append(fir[i])
  aa.sort()
for i in range(0,len(bir)):
  bb.append(bir[i])
  bb.sort()
print(aa)
print(bb)

if aa==bb:
  print(True)
else:
  print(False)

['a', 'a', 'a', 'g', 'm', 'n', 'r']
['a', 'a', 'a', 'g', 'm', 'n', 'r']
True


In [ ]:
# 17.	Write a program in Python to find prime factors of a given integer.

num=int(input('Enter the number '))
for i in range(1,num+1):
  if num%i==0:
    pf=0
    for j in range(2,i):
      if i%j==0:
        pf=1
        break
    if pf==0:
      print(i,end=" ")

Enter the number 6
1 2 3 

In [ ]:
# 18.	Python Program to count the occurrence of each character in string.

stringg='divyamaurya'
for i in range(0,len(stringg)):
  ab=stringg.count(stringg[i])
  print(f'{stringg[i]}:{ab}')

d:1
i:1
v:1
y:2
a:3
m:1
a:3
u:1
r:1
y:2
a:3
